In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import ast

In [2]:
df = pd.read_csv(r'D:\Data Analysis Project\New_MCD\Original - Copy\orders.csv')

In [3]:
df.head(10)

   order_id  customer_id           order_date store_city  total_amount
0         1          880  2025-05-28 15:18:00     krakow         79.06
1         2         8833  2025-01-25 08:35:00     poznan         67.68
2         3           19  2025-01-24 11:58:00     poznan         45.74
3         4         5321     08/02/2025 19:09     krakow         80.98
4         5         3642  2025-02-04 21:14:00     krakow         87.68
5         6         2286     30/03/2025 21:01     Poznan         59.58
6         7         5364  2025-05-22 17:06:00     gdansk         85.06
7         8         9857  2025-03-30 07:18:00     warsaw         19.15
8         9         8559  2025-02-14 14:03:00     warsaw         14.30
9        10         2084     06/02/2025 21:05     warsaw         69.65

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      50000 non-null  int64
 1   customer_id   50000 non-null  int64
 2   order_date    50000 non-null  str
 3   store_city    50000 non-null  str
 4   total_amount  46071 non-null  float64
dtypes: float64(1), int64(2), str(2)
memory usage: 1.9 MB

In [8]:
df['store_city'] = df['store_city'].str.capitalize()

In [18]:
df['order_date'].head(10)

0    2025-05-28 15:18:00
1    2025-01-25 08:35:00
2    2025-01-24 11:58:00
3       08/02/2025 19:09
4    2025-02-04 21:14:00
5       30/03/2025 21:01
6    2025-05-22 17:06:00
7    2025-03-30 07:18:00
8    2025-02-14 14:03:00
9       06/02/2025 21:05
Name: order_date, dtype: str

In [23]:
df['order_date'] = pd.to_datetime(df['order_date'], format='mixed', dayfirst=True)

In [24]:
df['order_date'].head(10)

0   2025-05-28 15:18:00
1   2025-01-25 08:35:00
2   2025-01-24 11:58:00
3   2025-02-08 19:09:00
4   2025-04-02 21:14:00
5   2025-03-30 21:01:00
6   2025-05-22 17:06:00
7   2025-03-30 07:18:00
8   2025-02-14 14:03:00
9   2025-02-06 21:05:00
Name: order_date, dtype: datetime64[us]

In [26]:
df['total_amount'] = df['total_amount'].fillna(df['total_amount'].mean())

In [27]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      50000 non-null  int64
 1   customer_id   50000 non-null  int64
 2   order_date    50000 non-null  datetime64[us]
 3   store_city    50000 non-null  str
 4   total_amount  50000 non-null  float64
dtypes: datetime64[us](1), float64(1), int64(2), str(1)
memory usage: 1.9 MB

In [28]:
df.head(10)

   order_id  customer_id          order_date store_city  total_amount
0         1          880 2025-05-28 15:18:00     Krakow         79.06
1         2         8833 2025-01-25 08:35:00     Poznan         67.68
2         3           19 2025-01-24 11:58:00     Poznan         45.74
3         4         5321 2025-02-08 19:09:00     Krakow         80.98
4         5         3642 2025-04-02 21:14:00     Krakow         87.68
5         6         2286 2025-03-30 21:01:00     Poznan         59.58
6         7         5364 2025-05-22 17:06:00     Gdansk         85.06
7         8         9857 2025-03-30 07:18:00     Warsaw         19.15
8         9         8559 2025-02-14 14:03:00     Warsaw         14.30
9        10         2084 2025-02-06 21:05:00     Warsaw         69.65

In [29]:
df.to_csv('orders_cleand.csv', index=False)